---
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONTAINER_IMG_VARIANT: ${CONTAINER_IMG_VARIANT:-}
    volumes:
      - ..:/workspace  # Mount the current directory into the container
    working_dir: /workspace  # Set the working directory in the container
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONPATH: /workspace  # Set the Python path
    stdin_open: true  # Keep stdin open to allow interactive sessions
    tty: true  # Allocate a pseudo-TTY
